### ISSUE TITLE
決定軟體的智慧財產授權條款

### ISSUE THREAD

**Issue by brlin-tw** [NTOUCS-Android-App-Design-1041-Team-16/NTOU-Wifi-AutoLogin#1]
智慧財產授權條款是軟體開發者授權給使用者之權利，從最基本的使用、散佈到更進一步的逆向工程與使用軟體的來源代碼(source code)等等。

您可以從 [Choose a License](http://choosealicense.com/) 網站察看各大授權條款的簡介。

個人推荐使用 [GNU GPL 第3版授權條款](http://www.chinasona.org/gnu/gnuv3-tc.html)，其允許使用者任意使用軟體與其來源代碼，但是要求將其修改並再散佈時必須附帶被修改版本的軟體來源代碼。

這個議題對於單純只是要完成學校課業的我們來說暫時不算很重要，但是在職場上使用第三方軟體程式庫進行開發時就需要注意是否有授權衝突的問題。

為什麼要一開始就討論？因為接下來若要修改的話是需要**經過所有提交過來源代碼的智慧財產權人(copyright holder)的同意**才能改的。

這項議題如果沒有後續討論的話會在 2015/11/27 自動結束。

**Comment by brlin-tw** [comment]
決定使用 GNU GPLv3

**Comment by a14578145** [comment]
同意使用 GNU GPLv3
