### ISSUE TITLE
專案說明文件 - 加上軟體開發要使用的軟體的說明

### ISSUE THREAD

**Issue by brlin-tw** [NTOUCS-Android-App-Design-1041-Team-16/NTOU-Wifi-AutoLogin#10]
一個多人合作開發的軟體專案，當然要讓所有貢獻者知道要怎麼開發XD

其中一個部份是如何在自己的系統上建構軟體開發環境，請在[如何對本專案做出貢獻](https://github.com/NTOUCS-Android-App-Design-1041-Team-16/NTOU-Wifi-AutoLogin/blob/master/CONTRIBUTING.markdown)文件中的[參與程式開發](https://github.com/NTOUCS-Android-App-Design-1041-Team-16/NTOU-Wifi-AutoLogin/blob/master/CONTRIBUTING.markdown#%E5%8F%83%E8%88%87%E7%A8%8B%E5%BC%8F%E9%96%8B%E7%99%BCprogramming)段落中新增一個子段落說明要如何在自己的電腦上建構開發環境。

最基本要包含：
- [ ] Android SDK
- [ ] Android Studio
- [ ] LibreOffice 或 Apache OpenOffice（我們目前用到 Draw 跟 Impress 兩組成元件）
- [ ] 任意 Markdown 文件編輯器

**Comment by a14578145** [comment]
以新增說明

**Comment by Lin-Buo-Ren** [comment]
@a14578145 

幾點要修正的地方：

**Comment by brlin-tw** [comment]
@a14578145 
有幾點可以修正／改善的地方：
1. 「建構開發環境」為「參與程式開發」段落底下的子標題，請將之設為第三級的子標題（語法請參考 http://markdown.tw以及該文件其他子段落）
2. 慣例來說為了美觀考量會在全形字元（含中文）與半形字元（英數字）之間插入一個空白使其有一定間隔
3. 超連結地址有問題，看起來你不是用 Markdown 標準的語法來設計超連結（字面上看起來像是 URL 的網址會自動轉為超連結是 GitHub 這個網站自己對 Markdown 做的擴充，不在 Markdown 標準內），請參考 http://markdown.tw 改用標準的語法（有多種語法可以達到同樣的效果，選任意一種即可
![_044](https://cloud.githubusercontent.com/assets/13408130/12011020/092f017a-acf9-11e5-828b-2ea00d5b22c2.png)

**Comment by a14578145** [comment]
修改了
這樣應該OK吧?

**Comment by brlin-tw** [comment]
@a14578145 OK
